GET http://127.0.0.1:3000/product-api/products

###
POST http://127.0.0.1:3000/product-api/products
Content-Type: application/json

{
    "productId" : 101,
    "name" : "laptop",
    "price" : 20000,
    "brand" : "Dell"
}

### get products by id
GET http://127.0.0.1:3000/product-api/products-id/101

### get product by brand
GET http://127.0.0.1:3000/product-api/products-brand/Dell

###
PUT http://127.0.0.1:3000/product-api/products
Content-Type: application/json

{
    "productId" : 101,
    "name" : "laptop",
    "price" : 25000,
    "brand" : "Dell"
}

###
DELETE http://127.0.0.1:3000/product-api/product/101