### read products
GET http://localhost:4000/product-api/products

### add products
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid" : 101,
    "productName" : "iphone-11",
    "price" : 35999
}

### get product by id
GET http://localhost:4000/product-api/products/697dce9bf4077f1e6367c357

### update product by id
PUT http://localhost:4000/product-api/products/697dd00f83f7bdbf78900bd6
Content-Type: application/json

{
    "pid" : 101,
    "productName" : "iphone-11",
    "price" : 32999
}